### PR TITLE
Tests against PHP 7.2

### PR DESCRIPTION
**Pull request by joaorobertopb**

### CODE REVIEW

**Comment by freekmurze** [comment]
Seems like the 7.2 test are failing? Could you fix that? Probably you need to update the PHPUnit constraint.

**Comment by joaorobertopb** [comment]
Done!

Fail in php 7.2 with the lower setup...

**Comment by joaorobertopb** [comment]
The tests are okay!

The failure is in "Generating Code Coverage Report in HTML Format"...

@freekmurze, any suggestion?

**Comment by freekmurze** [comment]
I'll fix this myself. Thanks!

**Pull request merged**
